export const EventTypes = {
  COMPETITION: "Competition",
  TECH: "Tech",
  WELFARE: "Welfare",
  SPORTS: "Sports",
  CULTURAL: "Cultural",
  WORKSHOP: "Workshop",
  WEBINAR: "Webinar",
  MEETUP: "Meetup",
  NETWORKING: "Networking",
  CONFERENCE: "Conference",
  SEMINAR: "Seminar",
  FUNDRAISER: "Fundraiser",
  EXHIBITION: "Exhibition",
  CHARITY: "Charity",
  ENTERTAINMENT: "Entertainment",
  SOCIAL: "Social",
  EDUCATIONAL: "Educational",
  BUSINESS: "Business",
  HACKATHON: "Hackathon",
};
